const ORDER_STATUS = {
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PAID_HELD: "PAID_HELD",
  DISPATCHED: "DISPATCHED",
  DELIVERED: "DELIVERED",
  RELEASED: "RELEASED",
  DISPUTED: "DISPUTED",
};

module.exports = { ORDER_STATUS };
